services:
  app:  # Changed from "production" to "app" to match staging
    container_name: clh-website-app-production
    image: clh-website-app:production
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app  # Added missing volume
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    command: npm start
    working_dir: /usr/src/app
    restart: always
    networks:
      - production_network

networks:
  production_network:
    driver: bridge
