version: "3.8"

services:
  app:
    container_name: clh-website-app-production
    image: clh-website-app:production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: production
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - .env.production:/usr/src/app/.env  # Optional, reinforces loading the .env file
    working_dir: /usr/src/app
    command: npm start
    restart: always
    networks:
      - production_network

networks:
  production_network:
    driver: bridge
