
services:
  app:
    container_name: clh-website-app-${NODE_ENV}
    image: clh-website-app:${NODE_ENV} 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  
    ports:
      - "${APP_PORT}:3000"  
    env_file:
      - .env.local
    command: npm start 
    working_dir: /usr/src/app
    restart: always
