services:
  app:
    container_name: clh-website-app-staging
    image: clh-website-app:staging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: staging
    ports:
      - "3001:3000"
    env_file:
      - .env.staging
    working_dir: /usr/src/app
    command: npm start
    restart: always
    networks:
      - staging_network

networks:
  staging_network:
    driver: bridge
