
services:
  app:
    container_name: clh-website-app-${NODE_ENV}
    image: clh-website-app:${NODE_ENV} 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  
    ports:
      - "${APP_PORT}:3000"  
    environment:
      - NODE_ENV=${NODE_ENV}
      - DOMAIN=${DOMAIN}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}  
      - DB_USER=${DB_USER} 
      - DB_PASS=${DB_PASS}
    command: npm start 
    working_dir: /usr/src/app
    restart: always
