name: Cd Pipeline

on:
  pull_request:
    branches:
      - master
      - develop
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build project
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ github.ref_name }}-node${{ matrix.node-version }}
        path: |
          dist/       # Include only build output
          package.json
          package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/master' && 'production' || 'staging') }}
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output-${{ github.ref_name }}-node18.x
        path: ./dist

    - name: Set environment variables
      run: |
        # Set environment-specific variables
        case "${{ github.ref }}" in
          refs/heads/master)  
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
        ;;
          refs/heads/develop)
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "NODE_ENV=staging" >> $GITHUB_ENV
          echo "COMPOSE_FILE=docker-compose.staging.yml" >> $GITHUB_ENV
        ;;
        *) 
        echo "Unknown branch, exiting." && exit 1
        ;;
        esac
    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.5
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
        APP_PORT: ${{ secrets.APP_PORT}}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        NEXT_PUBLIC_RECAPTCHA_SITE: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE }}
        NEXT_PUBLIC_RECAPTCHA_SECRET: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SECRET }}
      with:
        host: ${{ secrets.DBMART_HOST }}
        username: ${{ secrets.DBMART_USERNAME }}
        key: ${{ secrets.DBMART_SSH_KEY }}
        port: ${{ secrets.DBMART_PORT }}
        script: |
          cd ~/CLH_Website
          echo "Checkin out branch ${{ github.ref_name }}..."
          git checkout ${{ github.ref_name }}
          echo "Pulling latest changes..."
          git pull origin ${{ github.ref_name }}

          echo "🔍 Debugging Environment Variables:"
          echo "------------------------------------"
          echo "NODE_ENV: ${{env.NODE_ENV}}"
          echo "APP_PORT: ${{secrets.APP_PORT}}"
          echo "DOMAIN: ${{secrets.DOMAIN}}"
          echo "DB_HOST: ${{secrets.DB_HOST}}"
          echo "DB_NAME: ${{secrets.DB_NAME}}"
          echo "DB_USER: ${{secrets.DB_USER}}"
          echo "DB_PASS: (hidden)"
          echo "COMPOSE_FILE: ${{env.COMPOSE_FILE}}"
          echo "------------------------------------"

          # Ensure COMPOSE_FILE is set
          if [ -z "${{env.COMPOSE_FILE}}" ]; then
           echo "🚨 ERROR: COMPOSE_FILE is not set! Exiting..."
            exit 1
          fi

          echo "Stopping old containers..."
          echo "Using Compose file: ${{secrets.COMPOSE_FILE}}"
          docker compose -f ${{env.COMPOSE_FILE}} down

          echo "Setting environment variables..."
          export NODE_ENV=${{env.NODE_ENV}}
          export APP_PORT=${{secrets.APP_PORT}}
          export DOMAIN=${{secrets.DOMAIN}}
          export DB_HOST=${{secrets.DB_HOST}}
          export DB_NAME=${{secrets.DB_NAME}}
          export DB_USER=${{secrets.DB_USER}}
          export DB_PASS=${{secrets.DB_PASS}}
          export EMAIL_USER=${{secrets.EMAIL_USER}}
          export EMAIL_PASS=${{secrets.EMAIL_PASS}}
          export NEXT_PUBLIC_RECAPTCHA_SITE=${{secrets.NEXT_PUBLIC_RECAPTCHA_SITE}}
          export NEXT_PUBLIC_RECAPTCHA_SECRET=${{secrets.NEXT_PUBLIC_RECAPTCHA_SECRET}}

          echo "Building and starting containers..."
          docker compose -f ${{env.COMPOSE_FILE}}  up -d --remove-orphan

          echo "Restarting Nginx..."
          sudo systemctl reload nginx

          echo "Cleaning up old Docker images..."
          docker image prune -af --filter "until=24h"
