name: Cd Pipeline

on:
  pull_request:
    branches:
      - master
      - develop
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build project
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ github.ref_name }}-node${{ matrix.node-version }}
        path: |
          dist/
          package.json
          package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/master' && 'production' || 'staging') }}
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output-${{ github.ref_name }}-node18.x
        path: ./dist

    - name: Set environment variables
      run: |
        case "${{ github.ref }}" in
          refs/heads/master)  
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
            echo "APP_PORT=3000" >> $GITHUB_ENV
          ;;
          refs/heads/develop)
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "NODE_ENV=staging" >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.staging.yml" >> $GITHUB_ENV
            echo "APP_PORT=3001" >> $GITHUB_ENV
          ;;
          *) 
            echo "Unknown branch, exiting." && exit 1
          ;;
        esac

    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.5
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
        APP_PORT: ${{ env.APP_PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        NEXT_PUBLIC_RECAPTCHA_SITE: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE }}
        NEXT_PUBLIC_RECAPTCHA_SECRET: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SECRET }}
      with:
        host: ${{ secrets.DBMART_HOST }}
        username: ${{ secrets.DBMART_USERNAME }}
        key: ${{ secrets.DBMART_SSH_KEY }}
        port: ${{ secrets.DBMART_PORT }}
        script: |
          cd ~/CLH_Website
          echo "Checking out branch $(echo ${{ github.ref }} | sed 's|refs/heads/||')..."
          git checkout $(echo ${{ github.ref }} | sed 's|refs/heads/||')
          echo "Pulling latest changes..."
          git pull origin $(echo ${{ github.ref }} | sed 's|refs/heads/||')

          echo "Creating environment file..."
          cat > .env.local <<EOF
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          EMAIL_USER=${{ secrets.EMAIL_USER }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          NEXT_PUBLIC_RECAPTCHA_SITE=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE }}
          NEXT_PUBLIC_RECAPTCHA_SECRET=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SECRET }}
          EOF

          export NODE_ENV=${{ env.NODE_ENV }}
          export APP_PORT=${{ env.APP_PORT }}

          echo "Stopping old containers..."
          echo "Using Compose file: ${{ env.COMPOSE_FILE }}"
          docker compose -f ${{ env.COMPOSE_FILE }} down

          echo "Building and starting containers..."
          docker compose -f ${{ env.COMPOSE_FILE }} up -d --remove-orphans

          echo "Restarting Nginx..."
          sudo systemctl reload nginx

          echo "Cleaning up old Docker images..."
          docker image prune -af --filter "until=24h"
