name: Cd Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build project
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ github.ref_name }}-node${{ matrix.node-version }}
        path: |
          dist/       # Include only build output
          package.json
          package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output-${{ github.ref_name }}-node18.x
        path: ./dist

    - name: Set environment variables
      run: |
        echo "ENVIRONMENT=${{ github.ref_name == 'main' && 'production' || 'staging' }}" >> $GITHUB_ENV
        echo "DOMAIN=${{ secrets.DOMAIN }}" >> $GITHUB_ENV
        echo "APP_PORT=${{ secrets.APP_PORT }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
        echo "COMPOSE_FILE=${{secrets.COMPOSE_FILE}}" >> $GITHUB_ENV

    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DBMART_HOST }}
        username: ${{ secrets.DBMART_USERNAME }}
        key: ${{ secrets.DBMART_SSH_KEY }}
        port: ${{ secrets.DBMART_PORT }}
        script: |
          cd ~/CLH_Website
          echo "Pulling latest changes..."
          git pull origin ${{ github.ref_name }}

          echo "Setting environment variables..."
          export NODE_ENV=${{ env.ENVIRONMENT }}
          export DOMAIN=${{ env.DOMAIN }}
          export APP_PORT=${{ env.APP_PORT }}
          export COMPOSE_FILE=${{ env.COMPOSE_FILE }}
          export IMAGE_TAG=${{ env.ENVIRONMENT }}

          echo "Stopping old containers..."
          docker compose down

          echo "Building and starting containers..."
          docker compose build --no-cache
          docker compose up -d --remove-orphans

          echo "Restarting Nginx..."
          sudo systemctl reload nginx

          echo "Cleaning up old Docker images..."
          docker image prune -af --filter "until=24h"